// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"net/url"
	"strings"
	"ton618/internal/service"
)

func SidebarTree(notes []service.NoteItem, query string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(notes) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"text-center py-16\"><p class=\"text-zinc-600 text-sm\">Nenhuma nota encontrada.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"space-y-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, n := range notes {
				templ_7745c5c3_Err = SidebarNoteItem(n, query).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func SidebarNoteItem(n service.NoteItem, query string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-zinc-900/40 transition-colors group\"><div class=\"flex-1 min-w-0\"><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.SafeURL
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(getNoteLink(n.Arquivo)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 26, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" target=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(getTarget(n.Arquivo))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 26, Col: 91}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"block\"><span class=\"text-[13px] font-medium text-zinc-300 hover:text-sky-400 transition-colors truncate block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(getNoteIcon(n.Arquivo, n.Tags))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 28, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = highlightText(getFilename(n.Arquivo), query).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span><div class=\"flex flex-wrap gap-x-2 mt-0.5\"><span class=\"text-[10px] text-zinc-700\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(getDisplayType(n))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 31, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span></div></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(getVisibleTags(n.Tags)) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"hidden sm:flex gap-1 shrink-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, t := range getVisibleTags(n.Tags) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<span class=\"text-[9px] font-bold text-zinc-600 bg-zinc-800/40 px-1.5 py-0.5 rounded\">#")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(t)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 39, Col: 110}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<button type=\"button\" hx-prompt=\"Novo título:\" hx-post=\"/api/notes/rename\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(`{"old": "` + n.Arquivo + `"}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 44, Col: 124}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" hx-target=\"#sidebar-tree\" hx-swap=\"outerHTML\" class=\"text-zinc-700 hover:text-sky-400 transition-colors shrink-0 px-1 py-0.5 rounded-md hover:bg-zinc-900/60 text-xs max-sm:text-lg max-sm:px-2 max-sm:py-1\" title=\"Editar título\">✎</button> <button type=\"button\" hx-post=\"/api/notes/delete\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(`{"filename": "` + n.Arquivo + `"}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 48, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" hx-target=\"#sidebar-tree\" hx-swap=\"outerHTML\" hx-confirm=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue("Excluir " + n.Arquivo + "?")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/template/components/sidebar_tree.templ`, Line: 48, Col: 193}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" class=\"text-zinc-600 hover:text-red-400 text-sm font-semibold transition-colors shrink-0 px-2 py-1 rounded-md bg-zinc-950/80 hover:bg-zinc-900\" title=\"Excluir\">✕</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getFilename(path string) string {
	parts := strings.Split(path, "/")
	if len(parts) > 0 {
		name := parts[len(parts)-1]
		name = strings.TrimPrefix(name, "captura-")
		return strings.TrimSuffix(name, ".md")
	}
	return path
}

func getNoteLink(path string) string {
	if strings.HasPrefix(path, "pdfs/") {
		return "/file?name=" + url.QueryEscape(path)
	} else if strings.HasPrefix(path, "attachments/") || strings.HasPrefix(path, "archives/") {
		return "/file/download?name=" + url.QueryEscape(path)
	} else if strings.HasPrefix(path, "spreadsheet") {
		return "/spreadsheet?file=" + url.QueryEscape(path)
	} else if strings.HasPrefix(path, "drawing") {
		return "/drawing?file=" + url.QueryEscape(path)
	} else if strings.HasPrefix(path, "typst") {
		return "/typst?file=" + url.QueryEscape(path)
	} else if strings.HasPrefix(path, "mermaid") {
		return "/mermaid?file=" + url.QueryEscape(path)
	}
	return "/editor?file=" + url.QueryEscape(path)
}

func getTarget(path string) string {
	if strings.HasPrefix(path, "pdfs/") || strings.HasPrefix(path, "attachments/") || strings.HasPrefix(path, "archives/") {
		return "_blank"
	}
	return ""
}

func getNoteIcon(path string, tags []string) string {
	if strings.HasPrefix(path, "pdfs/") {
		return "📕"
	} else if strings.HasPrefix(path, "archives/") {
		return "💾"
	} else if strings.HasPrefix(path, "attachments/") {
		return "📦"
	}

	for _, t := range tags {
		switch strings.ToLower(t) {
		case "spreadsheet":
			return "📊"
		case "drawing":
			return "🎨"
		case "typst":
			return "📘"
		case "mermaid":
			return "🧜"
		case "youtube":
			return "🎬"
		case "artigo", "article":
			return "📰"
		case "captura", "capture":
			return "🌐"
		}
	}
	return "📄"
}

func getDisplayType(n service.NoteItem) string {
	if n.Type != "" {
		return n.Type
	}
	// Basic heuristics since n.Type isn't in NoteItem, relying on tags/path
	if strings.HasPrefix(n.Arquivo, "pdfs/") {
		return "pdf"
	}
	for _, t := range n.Tags {
		lowerT := strings.ToLower(t)
		if lowerT == "spreadsheet" || lowerT == "planilha" {
			return "planilha"
		} else if lowerT == "drawing" || lowerT == "desenho" {
			return "desenho"
		} else if lowerT == "typst" {
			return "typst"
		} else if lowerT == "mermaid" {
			return "mermaid"
		}
	}
	return "nota"
}

func getVisibleTags(tags []string) []string {
	var visible []string
	for _, t := range tags {
		t = strings.ToLower(t)
		if t != "typst" && t != "drawing" && t != "spreadsheet" && t != "mermaid" {
			visible = append(visible, t)
		}
	}
	return visible
}

func highlightText(text, query string) templ.Component {
	// For now, return plain text. To fully emulate the highlighter, we can build custom HTML.
	// If query is empty, just return the text
	if query == "" {
		return templ.Raw(templ.EscapeString(text))
	}

	queryLower := strings.ToLower(query)
	// Strip hashtags from query
	queryClean := ""
	for _, part := range strings.Fields(queryLower) {
		if !strings.HasPrefix(part, "#") {
			queryClean += part + " "
		}
	}
	queryClean = strings.TrimSpace(queryClean)

	if queryClean == "" {
		return templ.Raw(templ.EscapeString(text))
	}

	textLower := strings.ToLower(text)
	idx := strings.Index(textLower, queryClean)
	if idx == -1 {
		return templ.Raw(templ.EscapeString(text))
	}

	before := templ.EscapeString(text[:idx])
	match := templ.EscapeString(text[idx : idx+len(queryClean)])
	after := templ.EscapeString(text[idx+len(queryClean):])

	highlighted := before + `<span class="search-highlight text-sky-400 font-bold bg-sky-500/10 rounded px-0.5">` + match + `</span>` + after
	return templ.Raw(highlighted)
}

var _ = templruntime.GeneratedTemplate
